#pragma checksum "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c3271e717b2452cfbb488e69fed2f6efdae253d0"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_SalesOrderDetails_Index), @"mvc.1.0.view", @"/Views/SalesOrderDetails/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/SalesOrderDetails/Index.cshtml", typeof(AspNetCore.Views_SalesOrderDetails_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\MOONLAY\Assignment1\Assignment1\Views\_ViewImports.cshtml"
using Assignment1;

#line default
#line hidden
#line 2 "D:\MOONLAY\Assignment1\Assignment1\Views\_ViewImports.cshtml"
using Assignment1.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c3271e717b2452cfbb488e69fed2f6efdae253d0", @"/Views/SalesOrderDetails/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"85f0efab5ddbb0a5c18cf004c4d9e07516f4dd0e", @"/Views/_ViewImports.cshtml")]
    public class Views_SalesOrderDetails_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<Assignment1.Models.SalesOrderDetail>>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "SalesOrderDetails", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Create", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(57, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 3 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
  
    ViewData["Title"] = "Index";

#line default
#line hidden
            BeginContext(100, 114, true);
            WriteLiteral("\r\n<script>\r\n    $(document).ready(function () {\r\n        $(\'#dtBasicExample\').DataTable();\r\n    });\r\n</script>\r\n\r\n");
            EndContext();
#line 13 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
   
    ViewBag.Title = "Sales Order Details";

#line default
#line hidden
            BeginContext(266, 47, true);
            WriteLiteral("\r\n<h1>Sales Order Detail List</h1>\r\n\r\n<p>\r\n    ");
            EndContext();
            BeginContext(313, 72, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "c3271e717b2452cfbb488e69fed2f6efdae253d04563", async() => {
                BeginContext(371, 10, true);
                WriteLiteral("Create New");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(385, 180, true);
            WriteLiteral("\r\n</p>\r\n<table class=\"table table-striped table-bordered table-sm\" id=\"dtBasicExample\" cellspacing=\"0\" width=\"100%\"\">\r\n    <thead>\r\n        <tr>\r\n            <th>\r\n                ");
            EndContext();
            BeginContext(566, 44, false);
#line 26 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayNameFor(model => model.OrderQty));

#line default
#line hidden
            EndContext();
            BeginContext(610, 55, true);
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            EndContext();
            BeginContext(666, 45, false);
#line 29 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayNameFor(model => model.UnitPrice));

#line default
#line hidden
            EndContext();
            BeginContext(711, 55, true);
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            EndContext();
            BeginContext(767, 53, false);
#line 32 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayNameFor(model => model.UnitPriceDiscount));

#line default
#line hidden
            EndContext();
            BeginContext(820, 55, true);
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            EndContext();
            BeginContext(876, 45, false);
#line 35 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayNameFor(model => model.LineTotal));

#line default
#line hidden
            EndContext();
            BeginContext(921, 21, true);
            WriteLiteral("\r\n            </th>\r\n");
            EndContext();
            BeginContext(1045, 76, true);
            WriteLiteral("            <th>\r\n                <a asp-action=\"Index\" asp-route-sortDate=\"");
            EndContext();
            BeginContext(1122, 24, false);
#line 41 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
                                                     Write(ViewData["DateSortParm"]);

#line default
#line hidden
            EndContext();
            BeginContext(1146, 2, true);
            WriteLiteral("\">");
            EndContext();
            BeginContext(1149, 48, false);
#line 41 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
                                                                                Write(Html.DisplayNameFor(model => model.ModifiedDate));

#line default
#line hidden
            EndContext();
            BeginContext(1197, 59, true);
            WriteLiteral("</a>\r\n            </th>\r\n            <th>\r\n                ");
            EndContext();
            BeginContext(1257, 43, false);
#line 44 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayNameFor(model => model.Product));

#line default
#line hidden
            EndContext();
            BeginContext(1300, 55, true);
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
            EndContext();
            BeginContext(1356, 46, false);
#line 47 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayNameFor(model => model.SalesOrder));

#line default
#line hidden
            EndContext();
            BeginContext(1402, 86, true);
            WriteLiteral("\r\n            </th>\r\n            <th></th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");
            EndContext();
#line 53 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
 foreach (var item in Model) {

#line default
#line hidden
            BeginContext(1520, 48, true);
            WriteLiteral("        <tr>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(1569, 43, false);
#line 56 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.OrderQty));

#line default
#line hidden
            EndContext();
            BeginContext(1612, 55, true);
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(1668, 44, false);
#line 59 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.UnitPrice));

#line default
#line hidden
            EndContext();
            BeginContext(1712, 55, true);
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(1768, 52, false);
#line 62 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.UnitPriceDiscount));

#line default
#line hidden
            EndContext();
            BeginContext(1820, 55, true);
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(1876, 44, false);
#line 65 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.LineTotal));

#line default
#line hidden
            EndContext();
            BeginContext(1920, 21, true);
            WriteLiteral("\r\n            </td>\r\n");
            EndContext();
            BeginContext(2043, 34, true);
            WriteLiteral("            <td>\r\n                ");
            EndContext();
            BeginContext(2078, 47, false);
#line 71 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.ModifiedDate));

#line default
#line hidden
            EndContext();
            BeginContext(2125, 55, true);
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(2181, 47, false);
#line 74 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.Product.Name));

#line default
#line hidden
            EndContext();
            BeginContext(2228, 55, true);
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(2284, 62, false);
#line 77 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.SalesOrder.SalesOrderNumber));

#line default
#line hidden
            EndContext();
            BeginContext(2346, 55, true);
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
            EndContext();
            BeginContext(2402, 94, false);
#line 80 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ id = item.SalesOrderDetailId }));

#line default
#line hidden
            EndContext();
            BeginContext(2496, 20, true);
            WriteLiteral(" |\r\n                ");
            EndContext();
            BeginContext(2517, 98, false);
#line 81 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */id =item.SalesOrderDetailId }));

#line default
#line hidden
            EndContext();
            BeginContext(2615, 20, true);
            WriteLiteral(" |\r\n                ");
            EndContext();
            BeginContext(2636, 98, false);
#line 82 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
           Write(Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ id = item.SalesOrderDetailId }));

#line default
#line hidden
            EndContext();
            BeginContext(2734, 2, true);
            WriteLiteral("\r\n");
            EndContext();
            BeginContext(3011, 34, true);
            WriteLiteral("            </td>\r\n        </tr>\r\n");
            EndContext();
#line 88 "D:\MOONLAY\Assignment1\Assignment1\Views\SalesOrderDetails\Index.cshtml"
}

#line default
#line hidden
            BeginContext(3048, 24, true);
            WriteLiteral("    </tbody>\r\n</table>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<Assignment1.Models.SalesOrderDetail>> Html { get; private set; }
    }
}
#pragma warning restore 1591
